app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links: 
    - db
  volumes_from: 
    - webroot
  environment: 
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
#    DEBUG: "true"
  command: 
    - uwsgi
    - --socket /var/www/todobackend/todobackend.sock
    - --chmod-socket=666
    - --module todobackend.wsgi
    - --master
    - --die-on-term

test:
  image: 2251985/todobackend-specs
  links: 
    - nginx
  environment: 
    URL: http://nginx:8000/todos
    JUNIT_REPORT_PATH: /reports/acceptance.xml
  command: --reporter mocha-jenkins-reporter

nginx: 
  build: .
  dockerfile: Dockerfile.nginx
  links: 
    - app
  volumes: 
    - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
  ports: 
    - "8000:8000"
  volumes_from: 
    - webroot
     
webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes: 
    - /var/www/todobackend
  entrypoint: "true"

db:
  image: mysql:5.6
  expose: 
    - "3306"
  environment: 
    MYSQL_DATABASE: todobackend
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

agent:
  image: 2251985/docker-ansible
  links: 
    - db
  environment: 
    PROBE_HOST: db
    PROBE_PORT: "3306"
  command: ["probe.yml"]